/*
👋 Hi! This file was autogenerated by tslint-to-eslint-config.
https://github.com/typescript-eslint/tslint-to-eslint-config

It represents the closest reasonable ESLint configuration to this
project's original TSLint configuration.

We recommend eventually switching this configuration to extend from
the recommended rulesets in typescript-eslint.
https://github.com/typescript-eslint/tslint-to-eslint-config/blob/master/docs/FAQs.md

Happy linting! 💖
*/
// module.exports = {
//     "env": {
//         "browser": true,
//         "node": true
//     },
//     "extends": [
//         "prettier",
//         "prettier/@typescript-eslint"
//     ],
//     "parser": "@typescript-eslint/parser",
//     "parserOptions": {
//         "project": "tsconfig.json",
//         "sourceType": "module"
//     },
//     "plugins": [
//         "eslint-plugin-import",
//         "eslint-plugin-unicorn",
//         "eslint-plugin-jsdoc",
//         "eslint-plugin-no-null",
//         "eslint-plugin-prefer-arrow",
//         "@angular-eslint/eslint-plugin",
//         "@angular-eslint/eslint-plugin-template",
//         "eslint-plugin-react",
//         "@typescript-eslint",
//         "@typescript-eslint/tslint"
//     ],
//     "rules": {
//         "@angular-eslint/component-class-suffix": "error",
//         "@angular-eslint/component-max-inline-declarations": "error",
//         "@angular-eslint/component-selector": [
//             "error",
//             {
//                 "type": "element",
//                 "prefix": "",
//                 "style": "kebab-case"
//             }
//         ],
//         "@angular-eslint/contextual-lifecycle": "error",
//         "@angular-eslint/directive-class-suffix": "error",
//         "@angular-eslint/directive-selector": [
//             "error",
//             {
//                 "type": "attribute",
//                 "prefix": "",
//                 "style": "camelCase"
//             }
//         ],
//         "@angular-eslint/no-attribute-decorator": "error",
//         "@angular-eslint/no-conflicting-lifecycle": "error",
//         "@angular-eslint/no-forward-ref": "error",
//         "@angular-eslint/no-host-metadata-property": "error",
//         "@angular-eslint/no-input-prefix": "error",
//         "@angular-eslint/no-input-rename": "error",
//         "@angular-eslint/no-inputs-metadata-property": "error",
//         "@angular-eslint/no-lifecycle-call": "error",
//         "@angular-eslint/no-output-native": "error",
//         "@angular-eslint/no-output-on-prefix": "error",
//         "@angular-eslint/no-output-rename": "error",
//         "@angular-eslint/no-outputs-metadata-property": "error",
//         "@angular-eslint/no-pipe-impure": "error",
//         "@angular-eslint/no-queries-metadata-property": "error",
//         "@angular-eslint/pipe-prefix": "error",
//         "@angular-eslint/prefer-on-push-component-change-detection": "off",
//         "@angular-eslint/prefer-output-readonly": "error",
//         "@angular-eslint/relative-url-prefix": "error",
//         "@angular-eslint/template/banana-in-box": "error",
//         "@angular-eslint/template/cyclomatic-complexity": [
//             "error",
//             {
//                 "maxComplexity": 25
//             }
//         ],
//         "@angular-eslint/template/no-autofocus": "error",
//         "@angular-eslint/template/no-call-expression": "off",
//         "@angular-eslint/template/no-negated-async": "error",
//         "@angular-eslint/template/no-positive-tabindex": "error",
//         "@angular-eslint/use-component-selector": "off",
//         "@angular-eslint/use-component-view-encapsulation": "error",
//         "@angular-eslint/use-injectable-provided-in": "error",
//         "@angular-eslint/use-lifecycle-interface": "error",
//         "@angular-eslint/use-pipe-decorator": "error",
//         "@angular-eslint/use-pipe-transform-interface": "error",
//         "@typescript-eslint/adjacent-overload-signatures": "error",
//         "@typescript-eslint/array-type": [
//             "error",
//             {
//                 "default": "array-simple"
//             }
//         ],
//         "@typescript-eslint/await-thenable": "error",
//         "@typescript-eslint/ban-ts-comment": "error",
//         "@typescript-eslint/ban-types": [
//             "error",
//             {
//                 "types": {
//                     "Object,Avoid using the `Object` type. Did you mean `object`?": {
//                         "message": [
//                             "Function",
//                             "Avoid using the `Function` type. Prefer a specific function type, like `() => void`."
//                         ]
//                     }
//                 }
//             }
//         ],
//         "@typescript-eslint/consistent-type-assertions": "error",
//         "@typescript-eslint/consistent-type-definitions": "error",
//         "@typescript-eslint/dot-notation": "off",
//         "@typescript-eslint/explicit-member-accessibility": [
//             "off",
//             {
//                 "accessibility": "explicit"
//             }
//         ],
//         "@typescript-eslint/indent": [
//             "error",
//             4,
//             {
//                 "ArrayExpression": "first",
//                 "ObjectExpression": "first",
//                 "FunctionDeclaration": {
//                     "parameters": "first"
//                 },
//                 "FunctionExpression": {
//                     "parameters": "first"
//                 }
//             }
//         ],
//         "@typescript-eslint/member-delimiter-style": [
//             "error",
//             {
//                 "multiline": {
//                     "delimiter": "semi",
//                     "requireLast": true
//                 },
//                 "singleline": {
//                     "delimiter": "semi",
//                     "requireLast": false
//                 }
//             }
//         ],
//         "@typescript-eslint/member-ordering": "error",
//         "@typescript-eslint/naming-convention": "error",
//         "@typescript-eslint/no-empty-interface": "error",
//         "@typescript-eslint/no-explicit-any": "off",
//         "@typescript-eslint/no-extraneous-class": "error",
//         "@typescript-eslint/no-floating-promises": "error",
//         "@typescript-eslint/no-for-in-array": "error",
//         "@typescript-eslint/no-inferrable-types": [
//             "error",
//             {
//                 "ignoreParameters": true
//             }
//         ],
//         "@typescript-eslint/no-misused-new": "error",
//         "@typescript-eslint/no-namespace": "error",
//         "@typescript-eslint/no-non-null-assertion": "error",
//         "@typescript-eslint/no-param-reassign": "error",
//         "@typescript-eslint/no-parameter-properties": "off",
//         "@typescript-eslint/no-require-imports": "error",
//         "@typescript-eslint/no-this-alias": "error",
//         "@typescript-eslint/no-unnecessary-boolean-literal-compare": "error",
//         "@typescript-eslint/no-unnecessary-qualifier": "error",
//         "@typescript-eslint/no-unnecessary-type-arguments": "error",
//         "@typescript-eslint/no-unnecessary-type-assertion": "error",
//         "@typescript-eslint/no-unused-expressions": "error",
//         "@typescript-eslint/no-unused-vars": "error",
//         "@typescript-eslint/no-use-before-define": "error",
//         "@typescript-eslint/no-var-requires": "error",
//         "@typescript-eslint/prefer-for-of": "error",
//         "@typescript-eslint/prefer-function-type": "error",
//         "@typescript-eslint/prefer-namespace-keyword": "error",
//         "@typescript-eslint/prefer-readonly": "off",
//         "@typescript-eslint/promise-function-async": "error",
//         "@typescript-eslint/quotes": [
//             "error",
//             "single",
//             {
//                 "avoidEscape": true
//             }
//         ],
//         "@typescript-eslint/require-await": "error",
//         "@typescript-eslint/restrict-plus-operands": "error",
//         "@typescript-eslint/semi": [
//             "error",
//             "always"
//         ],
//         "@typescript-eslint/strict-boolean-expressions": [
//             "error",
//             {
//                 "allowNullable": true
//             }
//         ],
//         "@typescript-eslint/triple-slash-reference": [
//             "error",
//             {
//                 "path": "always",
//                 "types": "prefer-import",
//                 "lib": "always"
//             }
//         ],
//         "@typescript-eslint/type-annotation-spacing": "error",
//         "@typescript-eslint/unbound-method": "error",
//         "@typescript-eslint/unified-signatures": "error",
//         "arrow-body-style": "error",
//         "arrow-parens": [
//             "error",
//             "always"
//         ],
//         "brace-style": [
//             "error",
//             "1tbs"
//         ],
//         "class-methods-use-this": "error",
//         "comma-dangle": "error",
//         "complexity": [
//             "error",
//             {
//                 "max": 7
//             }
//         ],
//         "constructor-super": "error",
//         "curly": "error",
//         "default-case": "error",
//         "eol-last": "error",
//         "eqeqeq": [
//             "error",
//             "smart"
//         ],
//         "guard-for-in": "error",
//         "id-blacklist": [
//             "error",
//             "any",
//             "Number",
//             "number",
//             "String",
//             "string",
//             "Boolean",
//             "boolean",
//             "Undefined",
//             "undefined"
//         ],
//         "id-match": "error",
//         "import/no-default-export": "error",
//         "import/no-deprecated": "error",
//         "import/no-extraneous-dependencies": [
//             "error",
//             {
//                 "devDependencies": false
//             }
//         ],
//         "import/no-internal-modules": [
//             "error",
//             {
//                 "allow": [
//                     "@angular/cdk/*",
//                     "@angular/common/http/*",
//                     "@angular/material/*",
//                     "@angular/platform-browser/*",
//                     "rxjs/operators/*",
//                     "zone.js/*"
//                 ]
//             }
//         ],
//         "import/no-unassigned-import": "error",
//         "import/order": "error",
//         "jsdoc/check-alignment": "error",
//         "jsdoc/check-indentation": "error",
//         "jsdoc/newline-after-description": "error",
//         "jsdoc/no-types": "error",
//         "linebreak-style": [
//             "error",
//             "unix"
//         ],
//         "max-classes-per-file": [
//             "error",
//             1
//         ],
//         "max-len": [
//             "error",
//             {
//                 "code": 120
//             }
//         ],
//         "max-lines": [
//             "error",
//             300
//         ],
//         "new-parens": "error",
//         "newline-per-chained-call": "off",
//         "no-bitwise": "error",
//         "no-caller": "error",
//         "no-cond-assign": "error",
//         "no-console": "error",
//         "no-debugger": "error",
//         "no-duplicate-case": "error",
//         "no-duplicate-imports": "error",
//         "no-empty": [
//             "error",
//             {
//                 "allowEmptyCatch": true
//             }
//         ],
//         "no-eval": "error",
//         "no-extra-bind": "error",
//         "no-extra-semi": "off",
//         "no-fallthrough": "error",
//         "no-invalid-this": "error",
//         "no-irregular-whitespace": "error",
//         "no-magic-numbers": "off",
//         "no-multiple-empty-lines": "error",
//         "no-new-func": "error",
//         "no-new-wrappers": "error",
//         "no-null/no-null": "off",
//         "no-plusplus": "error",
//         "no-redeclare": "error",
//         "no-restricted-imports": "error",
//         "no-restricted-syntax": [
//             "error",
//             "ForInStatement"
//         ],
//         "no-return-await": "error",
//         "no-sequences": "error",
//         "no-shadow": [
//             "error",
//             {
//                 "hoist": "all"
//             }
//         ],
//         "no-sparse-arrays": "error",
//         "no-template-curly-in-string": "error",
//         "no-throw-literal": "error",
//         "no-trailing-spaces": "error",
//         "no-undef-init": "error",
//         "no-underscore-dangle": "error",
//         "no-unsafe-finally": "error",
//         "no-unused-labels": "error",
//         "no-useless-constructor": "error",
//         "no-var": "error",
//         "no-void": "error",
//         "object-shorthand": "error",
//         "one-var": [
//             "error",
//             "never"
//         ],
//         "padding-line-between-statements": [
//             "off",
//             {
//                 "blankLine": "always",
//                 "prev": "*",
//                 "next": "return"
//             }
//         ],
//         "prefer-arrow/prefer-arrow-functions": "error",
//         "prefer-const": "error",
//         "prefer-object-spread": "error",
//         "prefer-template": "error",
//         "quote-props": [
//             "error",
//             "consistent-as-needed"
//         ],
//         "radix": "error",
//         "react/jsx-curly-spacing": "off",
//         "react/jsx-equals-spacing": "off",
//         "react/jsx-wrap-multilines": "off",
//         "space-before-function-paren": [
//             "error",
//             {
//                 "anonymous": "never",
//                 "asyncArrow": "always",
//                 "named": "never"
//             }
//         ],
//         "space-in-parens": [
//             "error",
//             "never"
//         ],
//         "spaced-comment": [
//             "error",
//             "always",
//             {
//                 "markers": [
//                     "/"
//                 ]
//             }
//         ],
//         "unicorn/filename-case": "error",
//         "use-isnan": "error",
//         "yoda": "error",
//         "@typescript-eslint/tslint/config": [
//             "error",
//             {
//                 "rules": {
//                     "ban": [
//                         true,
//                         "eval",
//                         {
//                             "name": "$",
//                             "message": "please don't"
//                         },
//                         [
//                             "describe",
//                             "only"
//                         ],
//                         {
//                             "name": [
//                                 "it",
//                                 "only"
//                             ],
//                             "message": "don't focus tests"
//                         },
//                         {
//                             "name": [
//                                 "chai",
//                                 "assert",
//                                 "equal"
//                             ],
//                             "message": "Use 'strictEqual' instead."
//                         },
//                         {
//                             "name": [
//                                 "*",
//                                 "forEach"
//                             ],
//                             "message": "Use a regular for loop instead."
//                         },
//                         {
//                             "name": [
//                                 "*",
//                                 "_id",
//                                 "toString"
//                             ],
//                             "message": "Use 'toHexString' instead."
//                         },
//                         {
//                             "name": [
//                                 "*",
//                                 "hasOwnProperty"
//                             ],
//                             "message": "Use '!= null' instead."
//                         }
//                     ],
//                     "comment-type": [
//                         true,
//                         "singleline",
//                         "multiline",
//                         "doc",
//                         "directive"
//                     ],
//                     "contextual-decorator": true,
//                     "encoding": true,
//                     "import-destructuring-spacing": true,
//                     "import-spacing": true,
//                     "invalid-void": true,
//                     "match-default-export-name": true,
//                     "no-default-import": true,
//                     "no-dynamic-delete": true,
//                     "no-inferred-empty-object-type": true,
//                     "no-mergeable-namespace": true,
//                     "no-null-undefined-union": true,
//                     "no-promise-as-boolean": true,
//                     "no-restricted-globals": true,
//                     "no-tautology-expression": true,
//                     "no-unnecessary-callback-wrapper": true,
//                     "no-unused-css": true,
//                     "number-literal-format": true,
//                     "prefer-conditional-expression": true,
//                     "prefer-inline-decorator": true,
//                     "prefer-method-signature": true,
//                     "prefer-switch": true,
//                     "prefer-while": true,
//                     "prettier": true,
//                     "return-undefined": true,
//                     "static-this": true,
//                     "strict-comparisons": [
//                         true,
//                         {
//                             "allow-string-order-comparison": true
//                         }
//                     ],
//                     "strict-string-expressions": true,
//                     "switch-final-break": true,
//                     "template-accessibility-alt-text": true,
//                     "template-accessibility-elements-content": true,
//                     "template-accessibility-label-for": true,
//                     "template-accessibility-table-scope": true,
//                     "template-accessibility-valid-aria": true,
//                     "template-conditional-complexity": [
//                         true,
//                         4
//                     ],
//                     "template-mouse-events-have-key-events": true,
//                     "template-no-any": true,
//                     "template-no-distracting-elements": true,
//                     "template-use-track-by-function": true,
//                     "typedef": [
//                         true,
//                         "call-signature",
//                         "parameter",
//                         "property-declaration"
//                     ],
//                     "unnecessary-else": true,
//                     "whitespace": [
//                         true,
//                         "check-branch",
//                         "check-decl",
//                         "check-module",
//                         "check-operator",
//                         "check-preblock",
//                         "check-rest-spread",
//                         "check-separator",
//                         "check-type",
//                         "check-type-operator"
//                     ]
//                 }
//             }
//         ]
//     }
// };
