---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - typescript
  fixme:
    enabled: true
  reek:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - config.ru
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - '**.rb'
  - '**.scss'
  - '**.ts'
exclude_paths:
- 'bin/**/*'
- 'client/coverage/**/*'
- 'client/dist/**/*'
- 'client/node_modules/**/*'
- 'coverage/**/*'
- 'db/**/*'
- 'tmp/**/*'
- 'vendor/**/*'
