version: '2'
checks:
  method-complexity:
    config:
      threshold: 10
  method-lines:
    config:
      threshold: 30
plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        typescript:
          mass_threshold: 75
          filters:
          - "(ClassProperty _ (key (Identifier skaterStatColumns)) ___)"
        ruby:
          mass_threshold: 20
    exclude_paths:
      - '**/*.spec.ts'
  fixme:
    enabled: true
  reek:
    enabled: false
  rubocop:
    enabled: true
    channel: beta
exclude_patterns:
- 'bin/**/*'
- 'client/.angular/cache/**/*'
- 'client/coverage/**/*'
- 'client/dist/**/*'
- 'client/node_modules/**/*'
- 'coverage/**/*'
- 'db/**/*'
- 'tmp/**/*'
- 'vendor/**/*'
