---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  eslint:
    enabled: true
  fixme:
    enabled: true
  reek:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - config.ru
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - '**.rb'
  - '**.css'
  - '**.ts'
exclude_paths:
- 'bin/**/*'
- 'client/node_modules/**/*'
- 'coverage/**/*'
- 'db/**/*'
- 'tmp/**/*'
- 'vendor/**/*'
