version: '2'
plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        typescript:
          mass_threshold: 75
        ruby:
          mass_threshold: 15
    exclude_paths:
      - '**/*.spec.ts'
  fixme:
    enabled: true
  reek:
    enabled: false
  rubocop:
    enabled: true
exclude_patterns:
- 'bin/**/*'
- 'client/coverage/**/*'
- 'client/dist/**/*'
- 'client/node_modules/**/*'
- 'coverage/**/*'
- 'db/**/*'
- 'tmp/**/*'
- 'vendor/**/*'
