# Uses defaults from https://github.com/bbatsov/rubocop/blob/master/config/default.yml
# which is based on this ruby style guide https://github.com/bbatsov/ruby-style-guide

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'client/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.4

Metrics/LineLength:
  Max: 100

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%i": "[]"
