# Uses defaults from https://github.com/bbatsov/rubocop/blob/master/config/default.yml
# which is based on this ruby style guide https://github.com/bbatsov/ruby-style-guide

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'client/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  NewCops: enable
  TargetRubyVersion: 2.7

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 12

Metrics/MethodLength:
  Max: 10

Metrics/ClassLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%i": "[]"
