version: 2
jobs:
  backend:
    docker:
      - image: cimg/ruby:3.2.1-node
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: hockey-pool
          RAILS_ENV: test
      - image: cimg/postgres:12.9
        environment:
          POSTGRES_USER: hockey-pool
          POSTGRES_DB: db/hockey_pool_test_db
          POSTGRES_PASSWORD: ""
          POSTGRES_HOST_AUTH_METHOD: trust
    working_directory: ~/hockey-pool
    steps:
      - checkout
      - attach_workspace:
          at: ~/hockey-pool
      - restore_cache:
          keys:
            - hockey-pool-backend-{{ checksum "Gemfile.lock" }}
            - hockey-pool-backend-
      - run:
          name: Install gems
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler
            bundle check || bundle install
      - save_cache:
          key: hockey-pool-backend-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Run backend tests
          command: |
            bundle exec rake db:schema:load --trace
            bundle exec rake
      - run: bundle exec rubocop
  frontend-lint:
    docker:
      - image: cimg/ruby:3.2.1-node
    working_directory: ~/hockey-pool/client
    steps:
      - checkout:
          path: ~/hockey-pool
      - attach_workspace:
          at: ~/hockey-pool/client
      - restore_cache:
          keys:
            - hockey-pool-frontend-{{ checksum "package-lock.json" }}
            - hockey-pool-frontend-
      - run: npm install --legacy-peer-deps
      - run: npm run lint
      - save_cache:
          key: hockey-pool-frontend-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
  frontend-test:
    docker:
      - image: cimg/ruby:3.2.1-node
    working_directory: ~/hockey-pool/client
    steps:
      - checkout:
          path: ~/hockey-pool
      - attach_workspace:
          at: ~/hockey-pool/client
      - restore_cache:
          keys:
            - hockey-pool-frontend-{{ checksum "package-lock.json" }}
            - hockey-pool-frontend-
      - run: npm install --legacy-peer-deps
      - run: npm run test-ci
  frontend-build:
    docker:
      - image: cimg/ruby:3.2.1-node
    working_directory: ~/hockey-pool/client
    steps:
      - checkout:
          path: ~/hockey-pool
      - attach_workspace:
          at: ~/hockey-pool/client
      - restore_cache:
          keys:
            - hockey-pool-frontend-{{ checksum "package-lock.json" }}
            - hockey-pool-frontend-
      - run: npm install --legacy-peer-deps
      - run: npm run build-prod

not_master: &not_master
  filters:
    branches:
      ignore: master

workflows:
  version: 2

  commit:
    jobs:
      - backend:
          <<: *not_master
      - frontend-lint:
          <<: *not_master
      - frontend-test:
          <<: *not_master
      - frontend-build:
          <<: *not_master
